defmodule MauricioTest.Adapter do
  use ExUnit.Case
  alias Mauricio.News.Adapter.Panorama
  alias Mauricio.News.Adapter.Telegram

  test "panorama transform" do
    f = File.read!("test/test_data/panorama.html")
    {:ok, doc} = Floki.parse_document(f)

    assert [
             {_,
              "В Европарламенте призвали пересмотреть формат 8 марта из-за \"пропаганды бинарной гендерной системы\"",
              "https://panorama.pub/news/v-evroparlamente-prizvali-peresmotret-format-8-marta-iz-za-propagandy-binarnoj-gendernoj-sistemy"},
             {_,
              "В Белоруссии заблокируют YouTube за отказ продвигать в тренды двухчасовой фильм о планах Запада по срыву посевной",
              "https://panorama.pub/news/v-belorussii-zablokiruyut-youtube-za-otkaz-prodvigat-v-trendy-dvuxchasovoj-film-o-planax-zapada-po-sryvu-posevnoj"},
             {_, "Лукашенко объявил о проведении новых президентских выборов по почте",
              "https://panorama.pub/news/lukashenko-obyavil-o-provedenii-novyx-prezidentskix-vyborov-po-pochte"},
             {_,
              "Китайский министр получил 20 лет тюрьмы после того, как у его родителей нашли квартиру в Пекине",
              "https://panorama.pub/news/p43888"},
             {_,
              "«Вы обещали, что против меня майданов не будет»: Пашинян подал в суд на Джорджа Сороса",
              "https://panorama.pub/news/pashinyan-podal-v-sud-na-dzhordzha-sorosa"},
             {_, "ЕС потребовал добавить в мультфильм «Маша и медведи» ЛГБТ-персонажей",
              "https://panorama.pub/news/es-potreboval-dobavit-v-multfilm-masha-i-medvedi-lgbt-personazhej"},
             {_,
              "Цисгендерный казачий отряд Виталия Милонова задержал квирфеминистку, небинарного гея и одного нелегального мигранта на праздновании 8 марта",
              "https://panorama.pub/news/czisgendernyj-kazachij-otryad-vitaliya-milonova-zaderzhal-kvirfeministku-nebinarnogo-geya-i-odnogo-nelegalnogo-migranta-na-prazdnovanii-8-marta"},
             {_,
              "Калининградские таможенники поздравили женщин с 8 марта, раздавив на бульдозере партию санкционных цветов в виде цифры 8",
              "https://panorama.pub/news/kaliningradskie-tamozhenniki-pozdravili-zhenshhin-s-8-marta-razdaviv-na-buldozere-partiyu-sankczionnyx-czvetov-v-vide-czifry-8"},
             {_, "Суд признал лицо Залины Маршенкуловой овальным",
              "https://panorama.pub/news/sud-priznal-liczo-zaliny-marshenkulovoj-ovalnym"},
             {_, "Ивановские феминистки на 8 Марта сожгли цветочные магазины",
              "https://panorama.pub/news/ivanovskie-feministki-na-8-marta-sozhgli-czvetochnye-magaziny"},
             {_, "Илон Маск презентовал не требующий энергии подземный эко-холодильник",
              "https://panorama.pub/news/ilon-mask-prezentoval-ne-trebuyushhij-energii-podzemnyj-eko-xolodilnik"},
             {_, "Роботы Boston Dynamics создали профсоюз",
              "https://panorama.pub/news/roboty-boston-dynamics-sozdali-profsoyuz"},
             {_,
              "Директор Европейского института генетики: «Только расист может говорить, что наука чем-то обязана белым мышам»",
              "https://panorama.pub/news/direktor-evropejskogo-instituta-genetiki"},
             {_, "В Сколково разработали нано-дисплей, реагирующий на прикосновение пальца",
              "https://panorama.pub/news/p40517"},
             {_,
              "«Роскосмос» снабдит космонавтов инструкцией на случай вселения демонов в иностранных членов экипажа",
              "https://panorama.pub/news/roskosmos-snabdit-kosmonavtov-instrukcziej"},
             {_, "Россия введёт санкции на ввоз европейского семенного картофеля ",
              "https://panorama.pub/news/rossiya-vvedyot-sankczii-na-vvoz-i-prodazhu-evropejskogo-semennogo-kartofelya"},
             {_, "Чубайс призвал россиян вкладываться в биткоин",
              "https://panorama.pub/news/chubajs-prizval-rossiyan-vkladyvatsya-v-bitkoin"},
             {_, "На банкноте номиналом 15 рублей будет изображён Лахта-центр",
              "https://panorama.pub/news/na-banknote-nominalom-15-rublej-budet-izobrazhyon-laxta-czentr"},
             {_,
              "Тринадцать польских аквалангистов пострадали при попытке демонтажа «Северного потока-2»",
              "https://panorama.pub/news/trinadczat-polskix-akvalangistov-postradali-pri-popytke-demontazha-severnogo-potoka-2"},
             {_, "Adidas выпустит партию специальных спортивных костюмов для пациентов больниц",
              "https://panorama.pub/news/adidas-vypustit-partiyu"},
             {_, "ЕСПЧ восстановил в служении схиигумена Сергия",
              "https://panorama.pub/news/espch-vosstanovil-v-sluzhenii-sxiigumena-sergiya"},
             {_, "В Сколково разработали инновационную лопату для жарки блинов",
              "https://panorama.pub/32336-v-skolkovo-razrabotali.html"},
             {_, "В Смоленске на Масленицу сожгли чучело Навального",
              "https://panorama.pub/news/v-smolenske-na-masleniczu-sozhgli-chuchelo-navalnogo"},
             {_,
              "Прогрессивные СМИ бьют тревогу из-за возможного роста наркофобии после новосибирского инцидента",
              "https://panorama.pub/news/progressivnye-rossijskie-smi-byut-trevogu-iz-za-vozmozhnogo-rosta-narkofobii-posle-novosibirskogo-inczidenta"},
             {_,
              "МВД пообещало 8 марта не реагировать на все сообщения о домашнем насилии женщин в отношении мужчин",
              "https://panorama.pub/news/mvd-poobeshhalo-8-marta-ne-reagirovat-na-vse-soobshheniya-o-domashnem-nasilii-zhenshhin-v-otnoshenii-muzhchin"},
             {_,
              "Вася Обломов не смог стать почётным гражданином Магаданской области из-за отсутствия судимости",
              "https://panorama.pub/news/vasya-oblomov-ne-smog-stat-pochyotnym-grazhdaninom-magadanskoj-oblasti-iz-za-otsutstviya-sudimosti"}
           ] = Panorama.transform(doc)
  end

  test "telegram transform" do
    f = File.read!("test/test_data/telegram.html")
    {:ok, doc} = Floki.parse_document(f)

    assert [
             {~U[2021-03-12 06:00:01Z], "В Приморье пьяная ёлка снова подожгла людей",
              "https://t.me/neuralmeduza/1216"},
             {~U[2021-03-12 07:00:01Z], "РЖД переоформляет пассажиров в пианистов",
              "https://t.me/neuralmeduza/1217"},
             {~U[2021-03-12 08:00:02Z],
              "В России начали выдавать гробы, чтобы предотвратить теракты и убийства",
              "https://t.me/neuralmeduza/1218"},
             {~U[2021-03-12 09:00:01Z], "В Севастополе обнаружен ген троллейбуса",
              "https://t.me/neuralmeduza/1219"},
             {~U[2021-03-12 10:00:01Z], "Мосгорсуд решил обязать москвичей допивать пиво",
              "https://t.me/neuralmeduza/1220"},
             {~U[2021-03-12 11:00:01Z], "ЦИК попросил жителей Крымска сделать им минет",
              "https://t.me/neuralmeduza/1221"},
             {~U[2021-03-12 12:00:01Z],
              "Власти Симферополя предложили увеличить срок жизни портретами Кадырова",
              "https://t.me/neuralmeduza/1222"},
             {~U[2021-03-12 13:00:02Z], "МТС запустит мемы для борьбы с госслужащими",
              "https://t.me/neuralmeduza/1223"},
             {~U[2021-03-12 14:00:01Z],
              "В Дагестане открылся комбинат по производству афоризмов и песен",
              "https://t.me/neuralmeduza/1224"},
             {~U[2021-03-12 15:00:02Z],
              "Путин поручил правительству создать единую электронную карту вымирания",
              "https://t.me/neuralmeduza/1225"},
             {~U[2021-03-12 16:00:01Z],
              "Патриарх Кирилл объявил о начале «кровавого воскресения» в Москве",
              "https://t.me/neuralmeduza/1226"},
             {~U[2021-03-12 17:00:01Z], "Путин уволил курсор", "https://t.me/neuralmeduza/1227"},
             {~U[2021-03-12 18:00:01Z],
              "Роботы-собаки Федора Конюхова подарили бездомному волгоградцу нож",
              "https://t.me/neuralmeduza/1228"},
             {~U[2021-03-12 19:00:02Z],
              "Винни-Пух занял второе место на выборах президента России",
              "https://t.me/neuralmeduza/1229"},
             {~U[2021-03-13 07:00:02Z], "В Архангельской области нашли новую кожу Путина",
              "https://t.me/neuralmeduza/1230"},
             {~U[2021-03-13 08:00:02Z], "В США разработали гиперзвуковую бомбу в стиле рэп",
              "https://t.me/neuralmeduza/1231"},
             {~U[2021-03-13 09:00:01Z], "МТС запустит отечественный аналог COVID-19",
              "https://t.me/neuralmeduza/1232"},
             {~U[2021-03-13 10:00:01Z],
              "Коммунальные службы Подмосковья приняли решение приравнять москвичей к голубям",
              "https://t.me/neuralmeduza/1233"},
             {~U[2021-03-13 11:00:01Z],
              "Студенты Самарского госуниверситета подрались с реальностью",
              "https://t.me/neuralmeduza/1234"},
             {~U[2021-03-13 12:00:01Z],
              "МВД предложило ввести уголовную ответственность за административную ответственность",
              "https://t.me/neuralmeduza/1235"}
           ] = Telegram.transform(doc)
  end
end
