name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create config/secret.exs
      run: |
        echo "import Config
        
        config :nadia,
          token: \"xxx\"
        
        config :mauricio,
          cat_api_token: \"xxx\",
          dog_api_token: \"xxx\"
        " >${GITHUB_WORKSPACE}/config/secret.exs && cat ${GITHUB_WORKSPACE}/config/secret.exs
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
