name: release

on:
  release:
    types:
    - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create config/secret.exs
      run: |
        echo "import Config
        
        config :nadia,
          token: \"xxx\"
        
        config :mauricio,
          cat_api_token: \"xxx\",
          dog_api_token: \"xxx\"
        " >${GITHUB_WORKSPACE}/config/secret.exs && cat ${GITHUB_WORKSPACE}/config/secret.exs
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test

  deploy_prod:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - uses: mhanberg/gigalixir-action@0.1.0
        with:
          GIGALIXIR_USERNAME: ${{ secrets.PROD_GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.PROD_GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: ${{ secrets.PROD_GIGALIXIR_APP }}
          SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
